FROM wordpress:latest

# Adicione seus plugins e temas aqui

# Copie o arquivo de configuração do PHP
COPY php.ini /usr/local/etc/php/conf.d/

# Define a porta em que o WordPress será executado
EXPOSE 80

# Configurações do banco de dados
ENV WORDPRESS_DB_HOST=database:3306
ENV WORDPRESS_DB_USER=wordpress
ENV WORDPRESS_DB_PASSWORD=password
ENV WORDPRESS_DB_NAME=wordpress

# Comando de inicialização do WordPress
CMD ["apache2-foreground"]
