---
- hosts: '*'
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Log in to GitHub Container Registry
      docker_login:
        registry_url: ghcr.io
        username: leomaiaao
        password: "{{ LEO_GITHUB_TOKEN }}"

    - name: Start Database container
      docker_container:
        name: mysql
        image: ghcr.io/leomaiaao/mysql:latest
        state: started
        env:
          MYSQL_ROOT_PASSWORD: somewordpress
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress

    - name: Start WordPress container
      docker_container:
        name: wordpress
        image: ghcr.io/leomaiaao/wordpress:latest
        state: started
        env:
          WORDPRESS_DB_HOST: db:3306
          WORDPRESS_DB_USER: wordpress
          WORDPRESS_DB_PASSWORD: wordpress

    - name: Install Grafana
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - software-properties-common
        - wget
      tags:
        - grafana

    - name: Add Grafana APT key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present
      tags:
        - grafana

    - name: Add Grafana APT repository
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        filename: grafana.list
      tags:
        - grafana

    - name: Install Grafana
      apt:
        name: grafana
        state: present
      tags:
        - grafana

    - name: Start Grafana service
      service:
        name: grafana-server
        state: started
        enabled: yes
      tags:
        - grafana

    - name: Add Grafana datasource
      grafana_datasource:
        name: "{{ grafana_datasource_name }}"
        type: prometheus
        url: http://localhost:9090
        access: proxy
        is_default: true
        basic_auth_user: "{{ grafana_admin_user }}"
        basic_auth_password: "{{ grafana_admin_password }}"
        state: present
      tags:
        - grafana

    - name: Add Grafana dashboard
      grafana_dashboard:
        name: "{{ grafana_dashboard_name }}"
        file: /path/to/mydashboard.json
        folder_id: 0
        overwrite: true
        basic_auth_user: "{{ grafana_admin_user }}"
        basic_auth_password: "{{ grafana_admin_password }}"
        state: present
      tags:
        - grafana

  handlers:
    - name: Enable UFW
      ufw:
        rule: allow
        port: "80/tcp"
        state: enabled

    - name: Reload Nginx
      systemd:
        name: nginx
        state: restarted

    - name: Restart Docker
      systemd:
        name: docker
        state: restarted
